//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serveit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AmericanItem
    {
        public int A_id { get; set; }
        public string A_name { get; set; }
        public decimal A_price { get; set; }
    }
}
