//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serveit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ColdBeverage
    {
        public int Cb_Id { get; set; }
        public string Cb_name { get; set; }
        public Nullable<decimal> Cb_price { get; set; }
        public byte[] Cb_pic { get; set; }
    }
}
