//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Serveit.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ServeitDBEntities : DbContext
    {
        public ServeitDBEntities()
            : base("name=ServeitDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AmericanItem> AmericanItems { get; set; }
        public DbSet<BengaliItem> BengaliItems { get; set; }
        public DbSet<BreakFast> BreakFasts { get; set; }
        public DbSet<ChineseItem> ChineseItems { get; set; }
        public DbSet<ColdBeverage> ColdBeverages { get; set; }
        public DbSet<Dessert> Desserts { get; set; }
        public DbSet<DinnerCatagory> DinnerCatagories { get; set; }
        public DbSet<DrinksCategory> DrinksCategories { get; set; }
        public DbSet<HotBeverage> HotBeverages { get; set; }
        public DbSet<LunchCategory> LunchCategories { get; set; }
        public DbSet<OpenBeverage> OpenBeverages { get; set; }
        public DbSet<PrintReceipt> PrintReceipts { get; set; }
        public DbSet<ReceiptHistory> ReceiptHistories { get; set; }
        public DbSet<UserList> UserLists { get; set; }
        public DbSet<ViewReceiptDescription> ViewReceiptDescriptions { get; set; }
    }
}
